sudo: required
language: node_js
node_js:
- node
cache: yarn
before_script:
- npm --silent run input-search:test:sonar -- -Dsonar.organization=bikecoders -Dsonar.host.url=https://sonarcloud.io
  -Dsonar.login=$SONARCLOUD_TOKEN
script:
- npm run input-search:build-prod
before_deploy:
- npm run input-search:publish:copy-files
- cd dist/input-search
deploy:
  provider: npm
  email: bikecoders@gmail.com
  skip_cleanup: true
  api_key:
    secure: pm+SF0G6D4FGyTWC3jtOThJ73QzZfYoLbtoWOzTGHutprnNh+t/Lm0CBeCbKKVfEgPiDdIJMjX5cJUiBSIIdh1INjDjftS7PQbMOglHnCP1NoSQSL0o/RntM2j7naYg3lfPiaH8Pen5wId9XxXqfm1InNWa0yi6i9pgT0mj7Xu7AebM4j+YKWnlmz1ErNTB9cYHz0TZRuRpgGSqVosp5/61LhZhBrwYZSqnKvYETaL8+7zAaAR5AscO/j/qlYWJN6jvzJZeeXa0oFLxX96B85NhtHge9o1wICWxVWrrrjS1ufF+qHNb0Ou822TqavM28Oujk91/xHKyL6YD3RUer+f9em8ehAb3EBuU1bo3SekeFbb/O/s8Nm+37pYtyKx4o3AgVPHZkv3R0vuWvMHzxeKP89Ax1l6LBLi4HP+9Rw2E/i8ZzINSwVUlVAdPqkcOTi6sAf+fvvJzWckeImrOg9qoAiMOd4fGgEQdK1DIrKhK2U/fVQ9Y4rWZjGw/utqxMOCXzomV84ym9kcFSSJ94vMcpi8RmhhdIwJmdUqtjXseASXmnpJuwWuFmwhrr2p/l4Hfs70lDhfvCh2IbnkL106YnX0jvripWiwaqfnNvEBdRDHGXx6OL3v3dyBhBzv0ilPAPvmdpOOjM9FoVcx18bNubI/Iosq5rT0FltfGQWkE=
  on:
    tags: true
    repo: bikecoders/ngx-input-search
after_deploy:
- cd ../..
- yarn add ngx-input-search@latest --force && npm run deploy-gh-pages
