sudo: required
language: node_js
node_js:
- node
before_script:
- npm --silent run input-search:test:sonar -- -Dsonar.organization=bikecoders -Dsonar.host.url=https://sonarcloud.io
  -Dsonar.login=$SONARCLOUD_TOKEN
script:
- npm run input-search:build-prod
before_deploy:
- npm run input-search:publish:copy-files
- cd dist/input-search
deploy:
  provider: npm
  email: bikecoders@gmail.com
  skip_cleanup: true
  api_key:
    secure: BoXGiel88fe4ci//LZWrv5+zuj3lXKTNDXXNYPXSRHYihe70jqVZ+Q1Ne/wuLEVEeSVwr9g/ePaVOfF7LvqP4B2sP71+jW4eB4dW04wEDxt8SCWR/qHrSLpxSDrTkSXLBb3hFpjQMM4csU2fk3Ghlreb1hpzrYxuGhuIfeUCAYwTOwOIRDQOu5WhAdAH9LLOE0td2wvU0EKAtL2D2Eymcqa1Nj+/pj9hKPucLzaJTBWE7/EmlbmruDXEhDtMlykUViK1ohcdqzzmb7xUQ8OQOqtKPopO88PdZAdvT9wawLlVhY/he3NfHlFjiThJxaj6zDnmri18VwiVJzCxDSxX7gUPvL73/zA9sjupOTN6puWRKTf5GZAyPbZu47QsmXcm0cF7L8TJFyBz1I4HYeCym9CHDPPnQYLjlrsaT4/ie+YE8k79bGHNTvwlU4CelJ5Pn5GfoeNYRfDOmkn6jZjwvZYJSU9xPr6vkWA17y2nJedVwr+8z82ggq3BJ5HHpXLA+i9Midp8qIDugcB9R4iB+JRzQzk/EGk+7VQGc/JDdod7G0dS8BZBp1o5CIdOQhO3FLEc1lbeGiv3/K/4PJ0JE/NND2nR2TL5Y4T7hqc8bwHnA2UTgc+tqJlFIOmF937li4PNt+ws0mkNejrkAWhmkjdLz8QB+o0qx59OPutrpvQ=
  on:
    tags: true
    repo: bikecoders/ngx-input-search
after_deploy:
- cd ../..
- yarn upgrade ngx-input-search --force && yarn list ngx-input-search && npm run deploy-gh-pages
