sudo: required
language: node_js
node_js:
- node
before_script:
- npm --silent run input-search:test:sonar -- -Dsonar.organization=bikecoders -Dsonar.host.url=https://sonarcloud.io
  -Dsonar.login=$SONARCLOUD_TOKEN
script:
- npm run input-search:build-prod
before_deploy:
- npm run input-search:publish:copy-files
- cd dist/input-search
deploy:
  provider: npm
  email: bikecoders@gmail.com
  skip_cleanup: true
  api_key:
    secure: hnotYPyGreugPj6mgX9lkHmGdx5/Rt/d9oESYh4Nfj6Btw/J/tnIRvjGx8rpHBhUCUh+7aZtBRy16OI7/BSnMAzV2G8LYUBdckG341ZdLKJWbKsVwjZQx2EuuieacaeTTEt8n9Sm98ufZda758az4jF62m0OKYDT7DfUEX4HVsJaNQiHxkTZs9c/f2UR04yk34VdCQN1FdX+OSJooRXOI7szzG2buSQkXGOeM0GPiZARMl9c/ELh1cIrqQPnkUHOUezvNeg3Tt1a1r0MVcJ/MJyoPPCe/plP9pwqprZC6kZOyRSYcMBaVRzXBPhg19ZDWyq2S2+BvF8UmHFS117wTFOajFZqp9PNDt6zI1oXpohDGTIZqWd0PmHVZodo+H9RxGKbmKg81beE6WV9THAj2TTnJFlNopubXXAfxyzxM+7pzikZXFPxxjfmrsc+Kug/pGzOURNC/SUhOy4R4O8+btvbmbWPnN73Z5QBO3ADopnsXVcM5Gw33FDapvRnVI2D12Z4xF3PITTjT2AEubIQ/6Y5JBFmK4JlmnVS8jiPcz3LBquqdgW+jsVb/W4L+Ymu+41tFqkDvgfZhnMh9JaVER0CMuDAeNNLBH4OyTcsSCMk3xvYYsS+97xCzCnQbS4I3mNTSVXLJ27/IdnkRlMW5P1y7gxTJ4y7nz52aLJm/eo=
  on:
    tags: true
    repo: bikecoders/ngx-input-search
after_deploy:
- cd ../..
- yarn upgrade ngx-input-search --force && yarn list ngx-input-search && npm run deploy-gh-pages
